You will be provided with a partial code base and an issue statement explaining a problem to resolve.

<issue>
"?" in s3 table function doesn't work?
When i learn about "s3 table function" by folllowing https://clickhouse.com/docs/en/engines/table-engines/integrations/s3/, I found "?" does not work. 
The detailed tests are as follows. Is it a problem?
Obviously, "*" is workable.
The file name  in s3 is  test_1.parquet, test_2.parquet, test_3.parquet

```
:) show create table test_s3_test;

SHOW CREATE TABLE test_s3_test

Query id: 2975f0f5-53f2-4c07-8996-dec40458fae5

┌─statement───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE cos.test_s3_test
(
    `a` Int32,
    `b` String
)
ENGINE = S3('http://xxxxxxxx/testfile/test_?', ak, sk, 'Parquet') │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.

:) show create table test_s3_test2;

SHOW CREATE TABLE test_s3_test2

Query id: 621bf107-f651-41d6-993e-60ac96887da5

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE cos.test_s3_test2
(
    `a` Int32,
    `b` String
)
ENGINE = S3('http://xxxxxxxxx/testfile/test_?.parquet', ak, sk, 'Parquet') │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.002 sec.

 :) select count(*) from test_s3_test;

SELECT count(*)
FROM test_s3_test

Query id: 326c6eb2-a4bf-48b5-8c23-7827d0bf84f5

→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
0 rows in set. Elapsed: 0.697 sec.

Received exception from server (version 22.10.1):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: No response body.: While executing ParquetBlockInputFormat: While executing COSN. (S3_ERROR)

 :) select count(*) from test_s3_test2;

SELECT count(*)
FROM test_s3_test2

Query id: 82d747a6-3009-45cd-8a70-61a2f5cdfe0b

↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
0 rows in set. Elapsed: 0.225 sec.

Received exception from server (version 22.10.1):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: No response body.: While executing ParquetBlockInputFormat: While executing COSN. (S3_ERROR)
```
</issue>

I need you to solve the provided issue by generating a code fix that can be applied directly to the repository

Respond below:
