You will be provided with a partial code base and an issue statement explaining a problem to resolve.

<issue>
Dragonfly 1.30 crashes during Sidekiq CI
**Describe the bug**
Dragonfly 1.29 works, 1.30 crashes.

**To Reproduce**
Steps to reproduce the behavior:
1. Start docker image on macOS or Linux.
2. Run Sidekiq test suite.


```
I20250514 18:49:28.505877     1 dfly_main.cc:752] Starting dragonfly df-v1.30.0-561c0a47338791905f167de6faa12a38bc66a272
W20250514 18:49:28.506024     1 dfly_main.cc:791] SWAP is enabled. Consider disabling it when running Dragonfly.
I20250514 18:49:28.506065     1 dfly_main.cc:796] maxmemory has not been specified. Deciding myself....
I20250514 18:49:28.506071     1 dfly_main.cc:805] Found 3.43GiB available memory. Setting maxmemory to 2.74GiB
W20250514 18:49:28.506179     1 dfly_main.cc:375] Weird error 1 switching to epoll
I20250514 18:49:28.506762     1 proactor_pool.cc:149] Running 8 io threads
I20250514 18:49:28.511287     1 server_family.cc:839] Host OS: Linux 6.13.7-orbstack-00283-g9d1400e7e9c6 aarch64 with 8 threads
I20250514 18:49:28.511831     1 snapshot_storage.cc:182] Load snapshot: Searching for snapshot in directory: "/data"
W20250514 18:49:28.511868     1 server_family.cc:938] Load snapshot: No snapshot found
I20250514 18:49:28.515223    12 listener_interface.cc:101] sock[19] AcceptServer - listening on port 6379
F20250514 18:49:35.228960    13 reply_capture.cc:65] Check failed: stack_.empty() 
*** Check failure stack trace: ***
    @     0xaaaab9c6c104  google::LogMessage::SendToLog()
    @     0xaaaab9c64fe8  google::LogMessage::Flush()
    @     0xaaaab9c66924  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaab96ba33c  facade::CapturingReplyBuilder::Take()
    @     0xaaaab940840c  dfly::MultiCommandSquasher::SquashedHopCb()
    @     0xaaaab94090b4  _ZN4absl12lts_2024072219functional_internal12InvokeObjectIZN4dfly20MultiCommandSquasher15ExecuteSquashedEPN6facade17RedisReplyBuilderEEUlPT_PT0_E0_NS3_11Transaction14RunnableResultEJPSD_PNS3_11EngineShardEEEESA_NS1_7VoidPtrEDpNS1_8ForwardTIT1_E4typeE
    @     0xaaaab95d9ed8  dfly::Transaction::RunCallback()
    @     0xaaaab95dc6e8  dfly::Transaction::RunInShard()
    @     0xaaaab952309c  dfly::EngineShard::PollExecution()
    @     0xaaaab95d52d4  _ZNSt17_Function_handlerIFvvEZN4dfly11Transaction11DispatchHopEvEUlvE1_E9_M_invokeERKSt9_Any_data
    @     0xaaaab9ab4d20  util::fb2::FiberQueue::Run()
    @     0xaaaab962cc04  _ZN5boost7context6detail11fiber_entryINS1_12fiber_recordINS0_5fiberEN4util3fb219FixedStackAllocatorEZNS6_6detail15WorkerFiberImplIZN4dfly9TaskQueue5StartESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_JEEC4IS7_EESF_NS6_13FiberPriorityERKNS0_12preallocatedEOT_OSG_EUlOS4_E_EEEEvNS1_10transfer_tE
    @     0xaaaab9ad4f94  make_fcontext
*** SIGABRT received at time=1747248575 on cpu 2 ***
PC: @     0xffff8edef1f0  (unknown)  (unknown)
    @     0xaaaab9cc2214        480  absl::lts_20240722::AbslFailureSignalHandler()
    @     0xffff8f070868       4960  (unknown)
    @     0xffff8edaa67c        208  gsignal
    @     0xffff8ed97130         32  abort
    @     0xaaaab9c71bc4        336  google::DumpStackTraceAndExit()
    @     0xaaaab9c655e4        192  google::LogMessage::Fail()
    @     0xaaaab9c6c104         16  google::LogMessage::SendToLog()
    @     0xaaaab9c64fe8        208  google::LogMessage::Flush()
    @     0xaaaab9c66924         80  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaab96ba33c         16  facade::CapturingReplyBuilder::Take[abi:cxx11]()
    @     0xaaaab940840c        240  dfly::MultiCommandSquasher::SquashedHopCb()
    @     0xaaaab94090b4       1392  absl::lts_20240722::functional_internal::InvokeObject<>()
    @     0xaaaab95d9ed8         16  dfly::Transaction::RunCallback()
    @     0xaaaab95dc6e8        288  dfly::Transaction::RunInShard()
    @     0xaaaab952309c        352  dfly::EngineShard::PollExecution()
    @     0xaaaab95d52d4        336  std::_Function_handler<>::_M_invoke()
    @     0xaaaab9ab4d20        144  util::fb2::FiberQueue::Run()
    @     0xaaaab962cc04        304  boost::context::detail::fiber_entry<>()
[failure_signal_handler.cc : 345] RAW: Signal 5 raised at PC=0xffff8ed971ec while already in AbslFailureSignalHandler()
*** SIGTRAP received at time=1747248575 on cpu 2 ***
PC: @     0xffff8ed971ec  (unknown)  abort
    @     0xaaaab9cc2214        480  absl::lts_20240722::AbslFailureSignalHandler()
    @     0xffff8f070868       4960  (unknown)
    @     0xaaaab9c71bc4        336  google::DumpStackTraceAndExit()
    @     0xaaaab9c655e4        192  google::LogMessage::Fail()
    @     0xaaaab9c6c104         16  google::LogMessage::SendToLog()
    @     0xaaaab9c64fe8        208  google::LogMessage::Flush()
    @     0xaaaab9c66924         80  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaab96ba33c         16  facade::CapturingReplyBuilder::Take[abi:cxx11]()
    @     0xaaaab940840c        240  dfly::MultiCommandSquasher::SquashedHopCb()
    @     0xaaaab94090b4       1392  absl::lts_20240722::functional_internal::InvokeObject<>()
    @     0xaaaab95d9ed8         16  dfly::Transaction::RunCallback()
    @     0xaaaab95dc6e8        288  dfly::Transaction::RunInShard()
    @     0xaaaab952309c        352  dfly::EngineShard::PollExecution()
    @     0xaaaab95d52d4        336  std::_Function_handler<>::_M_invoke()
    @     0xaaaab9ab4d20        144  util::fb2::FiberQueue::Run()
    @     0xaaaab962cc04        304  boost::context::detail::fiber_entry<>()
src/sidekiq (main *) % 
```
</issue>

I need you to solve the provided issue by generating a code fix that can be applied directly to the repository

Respond below:
