You will be provided with a partial code base and an issue statement explaining a problem to resolve.

<issue>
mysql protocol does not support error during query execution
**Describe the bug**
 sql cannot read error msg by mysql client if table is on cluster

**Does it reproduce on recent release?**
server: clickhouse 21.2.4.6
client:  mysql client 8.0.20„ÄÅmsyql client 5.7.26 access through mysql_port

**How to reproduce**
- create table on cluster
```
CREATE TABLE `test`.`t7_all` ON CLUSTER cluster_1 (`id` Int64, `createtime` Date)  ENGINE = ReplicatedMergeTree('/clickhouse/cluster1/{layer}-{shard}/t7', '{replica}')  PARTITION BY createtime ORDER BY id SETTINGS index_granularity=8192;
```
- create table names  `test`.`t7_all`  again
```
CREATE TABLE `test`.`t7_all` ON CLUSTER cluster_1 (`id` Int64, `createtime` Date)  ENGINE = ReplicatedMergeTree('/clickhouse/cluster1/{layer}-{shard}/t7', '{replica}')  PARTITION BY createtime ORDER BY id SETTINGS index_granularity=8192;
```

**Expected behavior**
mysql client get error message same with clickhouse client: Table test.t7_all already exists

**Error message and/or stacktrace**
mysql client cannot read err message and report:
```
Lost connection to MySQL server during query
```

**Additional context**
Add any other context about the problem here.
</issue>

I need you to solve the provided issue by generating a code fix that can be applied directly to the repository

Respond below:
