diff --git a/tests/dragonfly/acl_family_test.py b/tests/dragonfly/acl_family_test.py
index d222d0c8c2ba..60070756b7a0 100644
--- a/tests/dragonfly/acl_family_test.py
+++ b/tests/dragonfly/acl_family_test.py
@@ -159,7 +159,7 @@ async def test_acl_cat_commands_multi_exec_squash(df_local_factory):
     await client.execute_command("MULTI")
     assert res == b"OK"
 
-    with pytest.raises(redis.exceptions.ResponseError):
+    with pytest.raises(redis.exceptions.NoPermissionError):
         await client.execute_command(f"SET x{x} {x}")
     await client.close()
 
@@ -186,7 +186,7 @@ async def test_acl_cat_commands_multi_exec_squash(df_local_factory):
     # return multiple errors for each command failed. Since the nature of the error
     # is the same, that a rule has changed we should squash those error messages into
     # one.
-    assert res[0].args[0] == "NOPERM: kk ACL rules changed between the MULTI and EXEC"
+    assert res[0].args[0] == "kk ACL rules changed between the MULTI and EXEC"
 
     await admin_client.close()
     await client.close()
@@ -213,7 +213,7 @@ async def test_acl_cat_commands_multi_exec_squash(df_local_factory):
     # NOPERM while executing multi
     await client.execute_command("MULTI")
 
-    with pytest.raises(redis.exceptions.ResponseError):
+    with pytest.raises(redis.exceptions.NoPermissionError):
         await client.execute_command(f"SET x{x} {x}")
 
     await admin_client.close()
